import FAQ from "@/components/FAQ";
import FeaturedHospital from "@/components/FeaturedHospital";
import Hero from "@/components/Hero";
import PopularDoctors from "@/components/PopularDoctors";
import Reviews from "@/components/Reviews";
import TopRatedHospital from "@/components/TopRatedHospital";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Hospital360",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <section className=" font-playwrite">
      <Hero />
      <FeaturedHospital />
      <TopRatedHospital />
      <Reviews />
      <PopularDoctors />
      <FAQ />
    </section>
  );
}
